/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.util.ArrayList;
import javax.swing.JTable;
import semestralka.Movie;
import semestralka.MovieLib;
import semestralka.MovieRecord;

/**
 *
 * @author DomikoX
 */
public class FilterWindow extends javax.swing.JFrame {

    private final JTable table;
    private final MovieLib movLib;

    /**
     * Creates new form FilterWindow
     *
     * @param table JTable where result should be showed
     * @param movLib MovieLib where MovieRecords are stored
     */
    public FilterWindow(JTable table, MovieLib movLib) {
        initComponents();
        this.table = table;
        this.movLib = movLib;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextFieldTitle = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldYear = new javax.swing.JTextField();
        jButtonFilter = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Set Filter");

        jLabel1.setText("Title");

        jTextFieldTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTitleActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "---", "Action", "Comedy", "Crime", "Fantasy", "Drama", "Thriller", "Sci-Fi", "Adventure", "Romance", "History", "Drama", "Biography", "Mystery", "Short", "Western", "War" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Genre");

        jLabel3.setText("From year");

        jButtonFilter.setText("Set filter");
        jButtonFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFilterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3)
                        .addComponent(jTextFieldTitle)
                        .addComponent(jComboBox1, 0, 172, Short.MAX_VALUE)
                        .addComponent(jTextFieldYear))
                    .addComponent(jButtonFilter))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonFilter)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTitleActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButtonFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFilterActionPerformed
        ArrayList<MovieRecord> helper = new ArrayList<>();

        boolean byTitle = !jTextFieldTitle.getText().isEmpty();
        boolean byGenre = !((String) jComboBox1.getSelectedItem()).equals("---");
        boolean byYear = !jTextFieldYear.getText().isEmpty();

        String title = jTextFieldTitle.getText();
        String genre = (String) jComboBox1.getSelectedItem();
        int year = byYear ? Integer.parseInt(jTextFieldYear.getText()) : 0;

        for (MovieRecord m : movLib.getMovies()) {
            if (!m.haveAllData()) {
                if (byTitle && m.getFilename().contains(jTextFieldTitle.getText())) {
                    helper.add(m);
                }
                continue;
            }
            int movieYear = parseYear(m.getMovie().getYear());
            if (byTitle && !(m.getFilename().contains(jTextFieldTitle.getText()) || m.getMovie().getTitle().equals(jTextFieldTitle.getText()))) {
                continue;
            }
            if (byGenre && !m.getMovie().getGenresInOneString().contains((String) jComboBox1.getSelectedItem())) {
                continue;
            }
            if (byYear && !(year <= movieYear)) {
                continue;
            }

            helper.add(m);

        }

        table.setModel(new MovieRecordTableModel(helper.isEmpty() ? movLib.getMovies() : helper));
        setVisible(false); //you can't see me!
        dispose(); //Destroy the JFrame object

    }//GEN-LAST:event_jButtonFilterActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonFilter;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextFieldTitle;
    private javax.swing.JTextField jTextFieldYear;
    // End of variables declaration//GEN-END:variables

    private int parseYear(String year) {
        try {
            if (year.length() == 4) {
                return Integer.parseInt(year);
            }
            if (year.length() == 5) {
                return Integer.parseInt(year.substring(0, 4));
            }
            if (year.length() == 9) {
                return Integer.parseInt(year.substring(5, 9));
            }
        } catch (Exception e) {
            return 0;
        }
        return 0;
    }
}
